//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMPS2000.Resource_File {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMPS2000.Resource_File.LabelNames", typeof(LabelNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Range: 0 to 9998).
        /// </summary>
        internal static string AddressRange {
            get {
                return ResourceManager.GetString("AddressRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog IOs.
        /// </summary>
        internal static string AnalogIO {
            get {
                return ResourceManager.GetString("AnalogIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate.
        /// </summary>
        internal static string baudrt {
            get {
                return ResourceManager.GetString("baudrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        internal static string btn_FindNext {
            get {
                return ResourceManager.GetString("btn FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string btnFindNext {
            get {
                return ResourceManager.GetString("btnFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string btnReplace {
            get {
                return ResourceManager.GetString("btnReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        internal static string btnReplaceAll {
            get {
                return ResourceManager.GetString("btnReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string cbMatchCase {
            get {
                return ResourceManager.GetString("cbMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole word only.
        /// </summary>
        internal static string cbMatchWholeWordOnly {
            get {
                return ResourceManager.GetString("cbMatchWholeWordOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Timeout (ms).
        /// </summary>
        internal static string comtout {
            get {
                return ResourceManager.GetString("comtout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Range: 0 to 65535).
        /// </summary>
        internal static string comtoutrange {
            get {
                return ResourceManager.GetString("comtoutrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Length.
        /// </summary>
        internal static string datalen {
            get {
                return ResourceManager.GetString("datalen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Range: 0 to 255).
        /// </summary>
        internal static string DeviceIdRange {
            get {
                return ResourceManager.GetString("DeviceIdRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital IOs.
        /// </summary>
        internal static string DigitalIO {
            get {
                return ResourceManager.GetString("DigitalIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Code.
        /// </summary>
        internal static string FunctionCode {
            get {
                return ResourceManager.GetString("FunctionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway.
        /// </summary>
        internal static string gateway {
            get {
                return ResourceManager.GetString("gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started with New Project.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Value.
        /// </summary>
        internal static string InitialValue {
            get {
                return ResourceManager.GetString("InitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        internal static string Inputs {
            get {
                return ResourceManager.GetString("Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO List.
        /// </summary>
        internal static string IOList {
            get {
                return ResourceManager.GetString("IOList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string ipadd {
            get {
                return ResourceManager.GetString("ipadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Logical Address.
        /// </summary>
        internal static string IsBtnShowLogical {
            get {
                return ResourceManager.GetString("IsBtnShowLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Retentive.
        /// </summary>
        internal static string IsRetentive {
            get {
                return ResourceManager.GetString("IsRetentive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace.
        /// </summary>
        internal static string lblFindAbdReplace {
            get {
                return ResourceManager.GetString("lblFindAbdReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what.
        /// </summary>
        internal static string lblFindWhat {
            get {
                return ResourceManager.GetString("lblFindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Project Name.
        /// </summary>
        internal static string lblProjectName {
            get {
                return ResourceManager.GetString("lblProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project Path.
        /// </summary>
        internal static string lblProjectPath {
            get {
                return ResourceManager.GetString("lblProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        internal static string lblReplaceWith {
            get {
                return ResourceManager.GetString("lblReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Range: 1 to 255).
        /// </summary>
        internal static string LengthRange {
            get {
                return ResourceManager.GetString("LengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Address.
        /// </summary>
        internal static string Logical_Address {
            get {
                return ResourceManager.GetString("Logical Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMPS 2000.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Interface.
        /// </summary>
        internal static string mininterface {
            get {
                return ResourceManager.GetString("mininterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Retries.
        /// </summary>
        internal static string noretries {
            get {
                return ResourceManager.GetString("noretries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Range: 1 to 9).
        /// </summary>
        internal static string noretriesrange {
            get {
                return ResourceManager.GetString("noretriesrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent Projects.
        /// </summary>
        internal static string OpenRecent {
            get {
                return ResourceManager.GetString("OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouputs.
        /// </summary>
        internal static string Outputs {
            get {
                return ResourceManager.GetString("Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        internal static string parity {
            get {
                return ResourceManager.GetString("parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PLC Model.
        /// </summary>
        internal static string PLCModel {
            get {
                return ResourceManager.GetString("PLCModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling (ms).
        /// </summary>
        internal static string polling {
            get {
                return ResourceManager.GetString("polling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Range: 0 to 3600000).
        /// </summary>
        internal static string pollingrange {
            get {
                return ResourceManager.GetString("pollingrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Range: 2 to 65534).
        /// </summary>
        internal static string PortRange {
            get {
                return ResourceManager.GetString("PortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Delay (ms).
        /// </summary>
        internal static string senddelay {
            get {
                return ResourceManager.GetString("senddelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave IP Address.
        /// </summary>
        internal static string SlaveIpAdd {
            get {
                return ResourceManager.GetString("SlaveIpAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Bit.
        /// </summary>
        internal static string stopbit {
            get {
                return ResourceManager.GetString("stopbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet.
        /// </summary>
        internal static string subnet {
            get {
                return ResourceManager.GetString("subnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
    }
}
